name: Backend - Build and Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: 654654369899.dkr.ecr.us-east-1.amazonaws.com/teste-elitonlima
  ECS_CLUSTER: test-elitonlima-ecs
  ECS_SERVICE: test-elitonlima-ecs-api
  TASK_FAMILY: test-elitonlima-ecs-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:latest .
          docker tag $ECR_REPOSITORY:latest $ECR_REPOSITORY:${{ github.sha }}

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REPOSITORY:latest
          docker push $ECR_REPOSITORY:${{ github.sha }}

      - name: Update ECS service to use new image
        uses: aws-actions/amazon-ecs-update-task-definition@v1
        with:
          task-family: ${{ env.TASK_FAMILY }}
          cluster: ${{ env.ECS_CLUSTER }}
          service: ${{ env.ECS_SERVICE }}
          container-name: backend
          image: ${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          force-new-deployment: true
